---
title: "First Knit"
author: "Skye Solis"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended high school at Lancaster High School, yes I did successfully graduate with a high school diploma. For myself, when it comes to comparing and contrasting the two subjects English and Math, I can say that English has to be the easiest subject. Mainly because the most difficult part of the subject would be the essays. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I do have a computer at home but I choose to complete my work on my iPad for the time being. In my honest opinion, I can rate myself a good 8 ½ knowing how smart I can be with a subject that I am interested in. My connection back at home is very good, I have 2 different internet connections therefore I always have internet when I need it which is 4 bars. 


## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
  The name that I prefer to be called and the name that I grew up with would be “Skye” pronounced (skiee like the sky above). I am also used to my professor calling me by my last name which is “Solis” pronounced (solees). 


 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
 
   
What I want to achieve in life is a successful and stable life. I want to be financially stable and happy in the life that I will be living for myself. The college subject that I believe best suits me is Science/Biology as I am a Biology major. The degree that I am willing to achieve in the near future is my Bachelor’s degree in Biology. 






## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   No, I have never gone to a foreign country sadly, if I do end up traveling to a foreign country it would definitely be Paris. I say this because ever since middle school I have been wanting to see the Eiffel tower. No, I have never been in the military, and from my experience living on this earth I have never known about everything that happens in the military, I am not educated when it comes to the military. 

  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




